### ISSUE TITLE
Ability to share stripped images directly with another application

### ISSUE THREAD

**Issue by szpak** [Tommy-Geenexus/ExifEraser#1]
Instead of saving a stripped image I would like to share it directly with an another application (e.g. Messenger or a Twitter client). It's faster and no extra files are created on a "disk" in that case.

Sample use case: Gallery -> ExifEraser -> Messenger/Twitter/...

**Comment by Tommy-Geenexus** [comment]
Sure, should be straightforward to implement.

**Comment by Tommy-Geenexus** [comment]
Closing this now that image sharing is implemented and will be published in the next update.

@szpak 
Just a technical FYI: Image sharing is done via intent's, which broadcast the images URI's.
Thus it is required to store the stripped images not in volatile, but in persistent memory
(Also, due to decoded images being memory hungry by default it is probably not the best idea to unnecessarily keep them in RAM).

**Comment by szpak** [comment]
Thanks.

About the memory consumption. Should it be automatically released once (let say) my MMS is sent? Or there could be some memory leaks over time?

**Comment by Tommy-Geenexus** [comment]
Currently the volatile memory will be released once the image has successfully been saved to persistent memory (thus before you are allowed to share the image).

There is no implementation of some kind of background job that deletes images periodically from persistent memory at the moment, and i don't think it's necessary.
Other apps cache their images in directories which are unknown to the user and perform periodic cleanups, but due to the fact that users manage their images themselves via a provider i think
there is no need for somethin alike in this project.

There will be no leaks, but it could be beneficial to delete images which solely are intented to be shared to prevent filling up your device's storage.

**Comment by szpak** [comment]
I've updated ExifEraser to 2.0.0 from Google Play and it doesn't seem to work (or I don't how to use it).

From [Simple Gallery](https://github.com/SimpleMobileTools/Simple-Gallery) I choose a photo, click a share icon, choose ExifEraser and I see "Save to" dialog (recent, drive, downloads) from the left (and I can save it there) - just as before. I don't know how to choose sharing with an another application.

What's even more strange, from the stock Motorola Gallery when I try to share a photo with ExifEraser I see just "Please select an image...". I don't know if it is a regression or it didn't work also in the previous version and I just wanted Gallery by Motorola as a fallback to Simple Gallery.

Moto G, Android 5.1.

P.S. The about dialog could display the current version of the application.

**Comment by Tommy-Geenexus** [comment]
@szpak 
The flow is as follows: Share via gallery -> Strip -> Save -> Share to any other app
You have to save the image before being able to share it,  also i tested it with Simple Gallery and it works just fine.

The Moto gallery is outdated i presume and doesn't set the required intent fields, thus not passing the intent validation. I could debug the exact issue but my time is limited, i'd suggest sticking to simple gallery for sharing.

**Comment by szpak** [comment]
Thanks for your explanations. I was able to successfully share a file.

The missing part was to save the file before sharing. I confused the "persistent memory" you mentioned with some other kind of memory not the one reported as `/storage/sdcard0`. Anyway, I can just save the files to some "known folder" and purge it occasionally if needed.

Not waste your time with Moto Gallery. I just mentioned it as a fallback to test this feature, but I use Simple Gallery on a daily basis which is more up-to-date.
